"""Add index

Revision ID: 0e2810d10e3d
Revises: 0fce0e4b42ba
Create Date: 2025-01-03 01:21:04.815684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2810d10e3d'
down_revision: Union[str, None] = '0fce0e4b42ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_nationalities_name', 'nationalities', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     op.drop_index('ix_nationalities_name', table_name='nationalities')
    # ### end Alembic commands ###

