"""Initial migration

Revision ID: 0fce0e4b42ba
Revises: 
Create Date: 2025-01-03 00:49:50.536647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fce0e4b42ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('population_estimate', sa.Integer(), nullable=True))
    op.add_column('states', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'population_estimate')
    op.drop_column('states', 'region')
    # ### end Alembic commands ###

